### ISSUE TITLE
bash, lmbench fail with "bug() bookkeep/shim_vma.c:205"

### ISSUE THREAD

**Issue by somename11111** [oscarlab/graphene#13]
Running bash with SGX produces the following output and then the process becomes unresponsive (has to be killed with SIGKILL):

```
$ ./bash.manifest.sgx bash_test.sh 
+ exec /home/user/projects/graphene/Pal/src/pal ./bash.manifest.sgx bash_test.sh
WARNING: no physical memory support, process creation will be slow.
bug() bookkeep/shim_vma.c:205
```

The same happens with lmbench in step `lat_proc exec`:
```
~/projects/graphene/LibOS/shim/test/apps/lmbench$ make test-graphene
[skipped]
lat_proc exec
WARNING: no physical memory support, process creation will be slow.
bug() bookkeep/shim_vma.c:205
```

**Comment by sgx1** [comment]
Same here.

**Comment by adombeck** [comment]
Executing any script with either bash or sh currently results in this error message:

    bug() bookkeep/shim_vma.c:245

I would love to see a fix for this.

**Comment by adombeck** [comment]
This seems also to be a problem with `exec`, like #59, so they might be related. But this happens earlier than the bug described in #59 (see backtrace below), and I could only trigger this when executing a script. For example:

```
LibOS/shim/test/apps/bash$ echo "/bin/ls" > bash_test.sh
LibOS/shim/test/apps/bash$ ./bash.manifest.sgx bash_test.sh
[...]
bug() bookkeep/shim_vma.c:245

Thread 2.1 "pal-Linux-SGX" received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7f7bbdfb8740 (LWP 10060)]
0x000000000bab829b in check_vma_flags (vma=0xb9a9138, flags=0xaf1751b) at bookkeep/shim_vma.c:245
245	        bug();
```

The backtrace is:

```
Thread 2.1 "pal-Linux-SGX" received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7f6ee2b30740 (LWP 10292)]
0x000000000bab829b in check_vma_flags (vma=0xb9a9138, flags=0xaf1751b) at bookkeep/shim_vma.c:245
245	        bug();
(gdb) bt
#0  0x000000000bab829b in check_vma_flags (vma=0xb9a9138, flags=0xaf1751b) at bookkeep/shim_vma.c:245
#1  0x000000000bab8c2c in __bkeep_munmap (addr=0xb960000, length=4096, flags=0xaf1751b)
    at bookkeep/shim_vma.c:432
#2  0x000000000bab8ddf in bkeep_munmap (addr=0xb960000, length=4096, flags=0xaf1751b)
    at bookkeep/shim_vma.c:469
#3  0x000000000bb342aa in shim_do_execve_rtld (hdl=0x0, argv=0x0, envp=0x0) at sys/shim_exec.c:124
#4  0x0000000000000000 in ?? ()
```

Interestingly, executing `/bin/ls` via `bash -c` instead causes the bug described in #59:

```
LibOS/shim/test/apps/bash$ ../bash.manifest.sgx -c "/bin/ls"
[    1] loading file:/bin/ls as runtime object at 0x0
[    1] bkeep_mmap: 0x400000-0x41e000
[    1] memory fault at 0x0 (IP = 0xbd98e83)
[    1] SIGSEGV handled
[    1] run signal handler 0xbac1725 (11, 0xaf12640, 0xaf126c8)
[    1] killed by SIGSEGV
```
Backtrace:
```
Thread 1 "pal-Linux-SGX" received signal SIGBUS, Bus error.
_wordcopy_fwd_aligned (dstp=<optimized out>, srcp=<optimized out>, len=976) at string/wordcopy.c:100
100	      ((op_t *) dstp)[2] = a1;
(gdb) bt
#0  _wordcopy_fwd_aligned (dstp=<optimized out>, srcp=<optimized out>, len=976) at string/wordcopy.c:100
#1  0x000000000bd96825 in memcpy (dstpp=0x61d000, srcpp=<optimized out>, len=7800) at string/memcpy.c:41
#2  0x000000000bd7f2b7 in file_map (handle=<optimized out>, addr=0xaf12e9f, prot=<optimized out>, 
    offset=<optimized out>, size=8192) at db_files.c:237
#3  0x000000000bd79305 in _DkStreamMap (handle=handle@entry=0xc3ba30c <mem_pool+4281004>, 
    paddr=paddr@entry=0xaf12eef, prot=<optimized out>, offset=<optimized out>, size=<optimized out>)
    at db_streams.c:549
#4  0x000000000bd79460 in DkStreamMap (handle=0xc3ba30c <mem_pool+4281004>, addr=<optimized out>, 
    prot=<optimized out>, offset=<optimized out>, size=<optimized out>) at db_streams.c:584
#5  0x000000000bace915 in chroot_mmap (hdl=0xb9b6258, addr=0xaf13007, size=8192, prot=3, flags=18, 
    offset=118784) at fs/chroot/fs.c:797
#6  0x000000000baede43 in __map_elf_object (file=0xb9b6258, fbp=0xaf13110, fbp_len=832, addr=0x0, 
    type=1, remap=0x0) at elf/shim_rtld.c:596
#7  0x000000000baef600 in __load_elf_object (file=0xb9b6258, addr=0x0, type=1, remap=0x0)
    at elf/shim_rtld.c:1051
#8  0x000000000baef44d in load_elf_object (file=0xb9b6258, addr=0x0, mapped=0) at elf/shim_rtld.c:1001
#9  0x000000000bb342db in shim_do_execve_rtld (hdl=0x0, argv=0x0, envp=0x0) at sys/shim_exec.c:134
#10 0x0000000000000000 in ?? ()
```

So the `bug() bookkeep/shim_vma.c:245` happens in the same call to `shim_do_execve_rtld()`, but earlier, in line 124 instead of 134.
