### ISSUE TITLE
HDFS get loginUserFromSubject encounter error

### ISSUE THREAD

**Issue by qiyuangong** [oscarlab/graphene#1661]
## Description of the problem

Trying to run HDFS read in enclave. But, HDFS filesystem encountered error when getting user and group error.
https://github.com/apache/hadoop/blob/trunk/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/UserGroupInformation.java#L710

## Steps to reproduce
Try read file with HDFS Filesystem API.

## Expected results
Read successful.

## Actual results
```bash

Exception in thread "main" java.io.IOException: failure to login
        at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:822)
        at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:774)                                                   at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:647)
        at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:2755)
        at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:2747)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2613)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:169)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:354)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:296)
        at com.intel.analytics.bigdl.utils.FileReader.<init>(File.scala:240)
        at com.intel.analytics.bigdl.utils.FileReader$.apply(File.scala:264)
        at com.intel.analytics.bigdl.utils.File$.readBytes(File.scala:198)
        at com.intel.analytics.bigdl.utils.serializer.ModuleLoader$.loadFromFile(ModuleLoader.scala:50)
Caused by: javax.security.auth.login.LoginException: java.lang.NullPointerException: invalid null input: name
        at jdk.security.auth/com.sun.security.auth.UnixPrincipal.<init>(UnixPrincipal.java:67)
        at jdk.security.auth/com.sun.security.auth.module.UnixLoginModule.login(UnixLoginModule.java:129)
        at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:726)
        at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:665)
        at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:663)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:663)
        at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:574)
        at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:797)
        at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:774)
        at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:647)
        at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:2755)
        at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:2747)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2613)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:169)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:354)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:296)
```

**Comment by qiyuangong** [comment]
Caused by getting username problem, resolved by adding etc and libnss* into trusted list.

Thanks to @llly
