### ISSUE TITLE
[Graphene LibOS] redis-py not work as redis' client app in enclave

### ISSUE THREAD

**Issue by kenplusplus** [oscarlab/graphene#1772]
## Description of the problem
A python app within graphene enclave failed to do redis.ping() via redis-py python lib with following exceptions. But it is works if using aioredis or redis-cli command line within enclave.

## Steps to reproduce

Test Case 1. Test redis ping via redis-py

1.1 Install redis-py in enclave via "pip3 install redis"
1.2 Put below sample test application in python3 enclave:
```
import os, redis                                                                
                                                                                
host = os.environ['REDIS_HOST']                                                
port = int(os.environ['REDIS_PORT']) 
                                                                                
redis_conn = redis.StrictRedis(host, port)                                      
print(redis_conn.ping())     
```  

Test Case 2. Test redis ping via aioredis
2.1 Install aioredis in enclave via "pip3 install aioredis"
2.2 Put below sample test application in python3 enclave:
```
import os                                                                       
import asyncio                                                                  
import aioredis                                                                 
                                                                                
host = os.environ['REDIS_HOST']                                                
port = int(os.environ['REDIS_PORT'])                                           
                                                                                
async def go():                                                                 
    redis = await aioredis.create_redis_pool(                                   
            'redis://%s:%d' % (host, port))                                     
    print(await redis.ping())                                                   
                                                                                
loop = asyncio.get_event_loop()                                                 
loop.run_until_complete(go())                                                   
```

Test Case 3. Test redis-cli in graphenized enclave bash via command "redis-cli -h <host> -p <port> ping"

## Expected results
The redis client in enclave for all test cases (1, 2, 3) should recieve "PONG" message from redis server.

## Actual results
In Test case 2, 3, the redis client recieved "PONG" message as expect sucessfully. But following exceptions reported for Test case 1
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 427, in read_from_socket
    bufflen = recv_into(self._sock, self._buffer)
  File "/usr/local/lib/python3.6/site-packages/redis/_compat.py", line 75, in recv_into
    return sock.recv_into(*args, **kwargs)
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/test-redis-py-sgx.py", line 9, in <module>
    print(redis_conn.ping())
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 1378, in ping
    return self.execute_command('PING')
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 470, in read_response
    self.read_from_socket()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 453, in read_from_socket
    (ex.args,))
redis.exceptions.ConnectionError: Error while reading from socket: (11, 'Resource temporarily unavailable')
```

## Additional information 

The full graphene debug log for Test case 1: 
[test-redis-py.log](https://github.com/oscarlab/graphene/files/5106715/test-redis-py.log)
The full graphene debug log for Test case 2:
[test_aioredis.log](https://github.com/oscarlab/graphene/files/5106717/test_aioredis.log)
The full graphene debug log for Test case 3:
[test-redis-cli.log](https://github.com/oscarlab/graphene/files/5106721/test-redis-cli.log)

**Comment by dimakuv** [comment]
@kenplusplus From the private correspondence, it seems that the bug is not in Graphene but in the used Redis-py library. Could you post some new information on this issue? (Or close it if you fixed the problem.)

**Comment by kenplusplus** [comment]
@dimakuv Sure, I will close this one firstly. It is caused by the redis-py's assumption - blocking mode. The solution is adding socket timeout or update implemetation.
