### ISSUE TITLE
Error while generating graphenized image using GSC.

### ISSUE THREAD

**Issue by Hackadon-crypto** [oscarlab/graphene#2184]
Hi, I met problems while generating graphenized docker image using GSC:

**Command:** 
```
# cd /home/graphene/Tools/gsc/test
# ./gsc build --insecure-args --build-arg https_proxy=$https_proxy --build-arg http_proxy=$http_proxy  mysecret:latest test/ubuntu18.04-mysecret.manifest
```
**Error:**
```
Step 18/20 : RUN chmod u+x apploader.sh     && python3 -B finalize_manifest.py / sh     && rm -f finalize_manifest.py

 ---> Running in d2d355b5c301
Found 11228 files in '/'.
LD_LIBRARY_PATH = '/usr/lib/x86_64-linux-gnu/libfakeroot:/usr/local/lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib:'
PATH = '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'.
Traceback (most recent call last):
  File "finalize_manifest.py", line 109, in <module>
    main(sys.argv)
  File "finalize_manifest.py", line 97, in main
    rendered_manifest = env.get_template(manifest).render()
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/loaders.py", line 197, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh

Failed to build graphenized image for mysecret:latest
```
**ubuntu18.04-mysecret.manifest:**
```
sgx.enclave_size = "4G"
sgx.thread_num = 8
```

So I ran the official examples in the test directory:
```
# cd /home/graphene/Tools/gsc/test
# make
```
**Error:**
```
Building graphenized image from base image ubuntu18.04-python3
Traceback (most recent call last):
  File "./gsc", line 12, in <module>
    sys.exit(main(sys.argv))
  File "./gsc.py", line 381, in main
    return args.command(args)
  File "./gsc.py", line 207, in gsc_build
    env, binary = prepare_env(base_image, image, args)
  File "./gsc.py", line 127, in prepare_env
    env.globals.update(config)
TypeError: 'NoneType' object is not iterable
Makefile:39: recipe for target 'gsc-ubuntu18.04-python3' failed
make[1]: *** [gsc-ubuntu18.04-python3] Error 1
make[1]: Leaving directory '/home/guodong/graphene/Tools/gsc/test'
Makefile:20: recipe for target 'all' failed
make: *** [all] Error 1
```

The Graphene is installed successfully, I've run the nginx and reddis case in the example directory.
Do you have any idea about the GSC error?

Thanks a lot!

**Comment by dimakuv** [comment]
Could you check the latest Graphene master (at least 544a7754f1446e9a7bc167eef1be5503c6e83122)? We just merged the GSC bug fixes. Hopefully this will resolve your issues.

**Comment by dimakuv** [comment]
Well, there is one more pending PR on GSC: https://github.com/oscarlab/graphene/pull/2174. This may also be needed to fix your issues.

**Comment by Hackadon-crypto** [comment]
Thanks dimakuv, #2174 patch works.
