### ISSUE TITLE
Error when building Pytorch example

### ISSUE THREAD

**Issue by chicolinux** [oscarlab/graphene#2293]
## Description of the problem
I get the following error message after trying to build the Pytorch example with make SGX=1

``` ../../Pal/src/host/Linux-SGX/signer/pal-sgx-sign \
	-libpal ../../Runtime/libpal-Linux-SGX.so \
	-key ../../Pal/src/host/Linux-SGX/signer/enclave-key.pem \
	-output pytorch.manifest.sgx \
	-manifest pytorch.manifest
Attributes:
    size:        0x100000000
    thread_num:  128
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0600000000000000
    attr.xfrm:   0300000000000000
    misc_select: 00000000
    date:        2021-04-06
Traceback (most recent call last):
  File "../../Pal/src/host/Linux-SGX/signer/pal-sgx-sign", line 19, in <module>
    sys.exit(main())
  File "/home/mguirao/graphene/python/graphenelibos/sgx_sign.py", line 830, in main
    return main_sign(manifest, args)
  File "/home/mguirao/graphene/python/graphenelibos/sgx_sign.py", line 750, in main_sign
    expanded_trusted_files = list(get_trusted_files(manifest).items())
  File "/home/mguirao/graphene/python/graphenelibos/sgx_sign.py", line 189, in get_trusted_files
    path = Path(resolve_uri(val, check_exist))
  File "/home/mguirao/graphene/python/graphenelibos/sgx_sign.py", line 153, in resolve_uri
    raise ManifestError('Cannot resolve ' + uri + ' or the file does not exist.')
graphenelibos.sgx_sign.ManifestError: Cannot resolve file:/usr/bin/python3.5 or the file does not exist.
Makefile:53: recipe for target 'sgx_outputs' failed
make: *** [sgx_outputs] Error 1
```
## Steps to reproduce
Run: make SGX=1
Ubuntu 18.4 Python 3.6.9

**Comment by mkow** [comment]
Hi, try building with `PYTHONVERSION=python3.6`.
Also, I think after #2288 we'll have Python version autodetection, so it will be a bit easier.
