### ISSUE TITLE
No module named 'generated_offsets'

### ISSUE THREAD

**Issue by kfxp12138** [oscarlab/graphene#2303]
## problem 
when I input **"make SGX=1 DEBUG=1"** in file  **"/graphene/python/graphenelibos/sgx_sign.py"**, I receive 
~~~
Traceback (most recent call last):
  File "/home/triple/graphene/python/graphenelibos/sgx_sign.py", line 19, in <module>
    from . import _offsets as offs # pylint: disable=import-error
ImportError: cannot import name '_offsets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/triple/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-sign", line 17, in <module>
    from graphenelibos.sgx_sign import main
  File "/home/triple/graphene/python/graphenelibos/sgx_sign.py", line 23, in <module>
    import generated_offsets as offs # pylint: disable=import-error
ModuleNotFoundError: No module named 'generated_offsets'
../../../../Scripts//../Pal/src/host/Linux-SGX/manifest.mk:26: recipe for target 'bootstrap_cpp.manifest.sgx.d' failed
make: *** [bootstrap_cpp.manifest.sgx.d] Error 1

~~~
I have no idea how to deal with the module 'generated_offset' ,has anyone met the same problem?
 
I can make true my SGX work successfully, and I follow the guide step by step, I am confused by the problem for a long while.

**THANKS for any help**

**Comment by mkow** [comment]
This is one of Graphene dependencies, please take a look at our Graphene building guide: https://graphene.readthedocs.io/en/latest/quickstart.html#quick-start-with-sgx-support.
