### ISSUE TITLE
Requirements are missing in .deb release of v1.2-rc1

### ISSUE THREAD

**Issue by Nirusu** [oscarlab/graphene#2563]
## Description of the problem
When using the new .deb packages of v1.2-rc1 on a relatively clean system using the instructions listed [in the release](https://github.com/oscarlab/graphene/releases/tag/v1.2-rc1), Graphene cannot be used correctly due to missing Python, protobuf & maybe Intel AESM packages, depending on the environment.

## Steps to reproduce
- Have a fairly clean system with essential development tools
- Install Graphene .deb pre-release as stated in the release notes (I used the out-of-tree DCAP package):
```
sudo apt-key adv --fetch-keys https://packages.grapheneproject.io/graphene.asc
echo 'deb [arch=amd64 signed-by=EA3C2D624681AC968521587A5EE1171912234070] https://packages.grapheneproject.io/ unstable main' | sudo tee /etc/apt/sources.list.d/graphene-unstable.list
sudo apt update
sudo apt install graphene-dcap     # for out-of-tree DCAP driver
```
- Build an application
- Try to sign it with Graphene

## Expected results
Graphene signs the application successfully.

## Actual results
Graphene fails due to missing packages, e.g.:
```
graphene-sgx-sign \
  --key signer-key.pem \
  --manifest redis-server.manifest \
  --output redis-server.manifest.sgx
Traceback (most recent call last):
   File "/usr/bin/graphene-sgx-sign", line 4, in <module>;
   from graphenelibos.sgx_sign import main
   File "/usr/lib/python3/dist-packages/graphenelibos/sgx_sign.py", line 16, in <module>;
   import toml
ModuleNotFoundError: No module named "toml";
make: *** [sgx_outputs] Error 1
Makefile:97: recipe for target 'sgx_outputs' failed
```

## Additional information
I know this is still a pre-release in early stages and the first package, just wanted to "note this down" here as an issue to be fixed for a future packaged release.

Ideally, the package can be directly used within a Docker environment as I am trying to use here (warning: it's a bit messy, haven't really cleaned it up):
https://github.com/edgelesssys/marblerun/commit/1ba7157244a8208df9873029a439dfe3edec6a7a

Note the commented out packages. These contain most of the ones needed to get Graphene to sign the application and return the SIGSTRUCT. However, AESM is still not completely installed as a requirement there. For experiments, I passed the AESM service from the host.

Also, when I am already here creating this issue: Any plans to also adjust your samples to get rid of the GRAPHENEDIR variable, which will not quite work with the release packages?

**Comment by dimakuv** [comment]
Thanks @Nirusu for pointing it out! Looks like work for @woju and @mkow.

> Any plans to also adjust your samples to get rid of the GRAPHENEDIR variable, which will not quite work with the release packages?

Do you mean in the Makefiles or in the Graphene manifest files?
- In the Makefiles, we still have `GRAPHENEDIR` but only as a "hack" to get to the default enclave-signing private key of the user.
- In the Graphene manifest files, `GRAPHENEDIR` was already removed from them.

For the Makefiles, we'll probably remove the mentions of `GRAPHENEDIR` and ask people to provide the private key explicitly.

See e.g. our Redis example:
- https://github.com/oscarlab/graphene/blob/master/Examples/redis/Makefile (`GRAPHENEDIR` used as a hack)
- https://github.com/oscarlab/graphene/blob/master/Examples/redis/redis-server.manifest.template (no `GRAPHENEDIR`)

Btw, I just noticed that we have stale GRAPHENEDIR mentions in the comments in manifest files :) We'll remove these.

**Comment by Nirusu** [comment]
Yup, I meant the references in the Makefiles! I know that these were mainly used as a hack to link to the private key used for enclave signing, however one other... let's say, implicit... reference to GRAPHENEDIR are the included in the Makefile, such as in [line 39 of the Redis Makefile](https://github.com/oscarlab/graphene/blob/202b77ace19e13bffd24959e3a6dc46dc9066ec9/Examples/redis/Makefile#L39) you linked. 

They point outside of the example directory and the include one also includes another (Makefile.configs -> Makefile.host), so unfortunately right now you cannot just simply download a folder of a specific sample, but rather need the folder, patch the private key thing and then also provide the include to build a sample.

So far when you had to build Graphene from source everytime, this was not this bad but for a package release cloning the whole repo (or scrapbooking every piece together) is kind of awkward in my opinion.

But luckily, these are not really deal breakers and are easy to modify. It's just the requirements one that's kind of awkward right now as we cannot really expect users to gather all requirements together. Would be cooler if the package automatically flags all dependencies :)

**Comment by dimakuv** [comment]
@Nirusu Thanks again for the comments! Indeed, the problem of GRAPHENEDIR in Makefiles is annoying.

I started fixing Examples: https://github.com/oscarlab/graphene/pull/2566. This PR is more about clean up of the manifest files.

I will create another PR to remove GRAPHENEDIR and generally cleanup Makefiles in examples. Probably today/tomorrow.

**Comment by dimakuv** [comment]
@Nirusu I created https://github.com/oscarlab/graphene/pull/2582 to decouple Examples' Makefiles from Graphene-internal paths and files.

**Comment by Nirusu** [comment]
@dimakuv Thank you! Looks good to me, an alternative for SGX_SIGNER_KEY as you noted would still be preferable, but since that's definable from the environment anyway, that's no biggie.

One alternative I could suggest here is just randomly generating the key as part of the make, and alternatively maybe setting it globally in the example directory if you want to keep the same MRSIGNER between the examples. Or am I missing a specific use case here?

**Comment by dimakuv** [comment]
> One alternative I could suggest here is just randomly generating the key as part of the make, and alternatively maybe setting it globally in the example directory if you want to keep the same MRSIGNER between the examples. Or am I missing a specific use case here?

Well, yeah, generating a dummy key as part of the make is also reasonable. Let's see what other Graphene maintainers think.

**Comment by mkow** [comment]
Not sure if we want to do this, it may suggest to our users reading the examples that the signing keys are per-enclave or per-build.
Maybe it's just the error message with missing `SGX_SIGNER_KEY` we should fix? I don't think we have any nice handling of this case.

**Comment by dimakuv** [comment]
> Maybe it's just the error message with missing SGX_SIGNER_KEY we should fix? I don't think we have any nice handling of this case.

@mkow, you should take a look at #2582. In that PR, I do this in each Example:
```
SGX_SIGNER_KEY ?= ../../Pal/src/host/Linux-SGX/signer/enclave-key.pem
```

In other words, `SGX_SIGNER_KEY` envvar points to the dummy signing key generated during Graphene build (if the user follows our QuickStart guide) by default. But ideally, for production purposes, the user will overwrite this dummy default with her own key: `SGX_SIGNER_KEY=<path-to-my-signing-key> make`.

So the question here is: do we keep this default, or do we add a new Makefile rule to generate a new dummy key, or do we error out in the Makefile if no `SGX_SIGNER_KEY` is specified.

**Comment by mkow** [comment]
Why not both? I.e. keep this default, but if `SGX_SIGNER_KEY` doesn't exists after this conditional substitution then we error out?

**Comment by Nirusu** [comment]
Why not auto-generate a key globally in the example folder, if non is existing? Shouldn't that suggest that the key is not bound per enclave or per build?

I mean, if you plan on keeping building Graphene in the quickstart guide, it will probably be fine, but if you want to decouple examples and/or plan on using prebuilt releases in the quickstart guide, I think generating a key if non exists makes more sense rather than just trying to say the user "Hey, you need to provide one!", unless you plan to make this some kind of educational step in getting started with Graphene.

**Comment by dimakuv** [comment]
> Why not auto-generate a key globally in the example folder, if non is existing?

Do you mean add this logic to each of the examples' Makefiles? This feels to me like too much hand-holding. Also, auto-generating a private key in the Makefile sounds like a bad idea from the security perspective -- the users don't even notice that a very important security artifact was created in some random fashion.

For now, we went with the "error out" approach in Makefiles, see https://github.com/oscarlab/graphene/pull/2582

**Comment by Nirusu** [comment]
Yes, this was my idea, but I also get your point about this being too much hand holding. As long as one can easily find the issue (e.g. noted in docs, easy googleable which kind of key you need (RSA-3072)), I think that's sufficient.

**Comment by mkow** [comment]
I agree with @dimakuv, this step is something our users should be aware of, not something we should do behind their back automatically. They need to know that running enclaves requires a private key from the developer and that they should generate one.

**Comment by woju** [comment]
> @woju Please take a look at this at some point. We'll need to add the
> missing required packages to our `.deb` package.

Yes, I remember about this. Don't you want to move this issue to gramine repo?

-- 
pozdrawiam / best regards
Wojtek Porczyk
Gramine / Invisible Things Lab
 
 I do not fear computers,
 I fear lack of them.
    -- Isaac Asimov
