### ISSUE TITLE
Bash example in CentOS failing with permission denied /usr/bin/etc/gshadow during graphene-sgx-sign stage

### ISSUE THREAD

**Issue by jinengandhi-intel** [oscarlab/graphene#2624]
## Description of the problem
Bash example fails with the following error during signing on CentOS machine:

```
[intel1@localhost bash]$ ARCH_LIBDIR=/lib64 make SGX=1
graphene-manifest \
        -Dlog_level=error \
        -Dexecdir=/usr/bin \
        -Darch_libdir=/lib64 \
        manifest.template >bash.manifest
graphene-sgx-sign \
        --key ../../Pal/src/host/Linux-SGX/signer/enclave-key.pem \
        --manifest bash.manifest \
        --output bash.manifest.sgx
Attributes:
    size:        0x10000000
    thread_num:  4
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0600000000000000
    attr.xfrm:   0300000000000000
    misc_select: 00000000
    date:        2021-08-05
Traceback (most recent call last):
  File "/usr/local/bin/graphene-sgx-sign", line 5, in <module>
    sys.exit(main())
  File "/usr/local/lib64/python3.6/site-packages/graphenelibos/sgx_sign.py", line 824, in main
    return main_sign(manifest, args)
  File "/usr/local/lib64/python3.6/site-packages/graphenelibos/sgx_sign.py", line 743, in main_sign
    expanded_trusted_files = list(get_trusted_files(manifest).items())
  File "/usr/local/lib64/python3.6/site-packages/graphenelibos/sgx_sign.py", line 195, in get_trusted_files
    hash_ = get_hash(target).hex()
  File "/usr/local/lib64/python3.6/site-packages/graphenelibos/sgx_sign.py", line 159, in get_hash
    with open(filename, 'rb') as file:
PermissionError: [Errno 13] Permission denied: '/usr/bin/etc/gshadow'
```

The same command passes when run with sudo.

```
[intel1@localhost bash]$ sudo ARCH_LIBDIR=/lib64 make SGX=1
graphene-sgx-sign \
        --key ../../Pal/src/host/Linux-SGX/signer/enclave-key.pem \
        --manifest bash.manifest \
        --output bash.manifest.sgx
Attributes:
    size:        0x10000000
    thread_num:  4
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0600000000000000
    attr.xfrm:   0300000000000000
    misc_select: 00000000
    date:        2021-08-05
Memory:
    000000000f5b0000-0000000010000000 [REG:R--] (manifest) measured
    000000000f590000-000000000f5b0000 [REG:RW-] (ssa) measured
    000000000f58c000-000000000f590000 [TCS:---] (tcs) measured
    000000000f588000-000000000f58c000 [REG:RW-] (tls) measured
    000000000f548000-000000000f588000 [REG:RW-] (stack) measured
    000000000f508000-000000000f548000 [REG:RW-] (stack) measured
    000000000f4c8000-000000000f508000 [REG:RW-] (stack) measured
    000000000f488000-000000000f4c8000 [REG:RW-] (stack) measured
    000000000f478000-000000000f488000 [REG:RW-] (sig_stack) measured
    000000000f468000-000000000f478000 [REG:RW-] (sig_stack) measured
    000000000f458000-000000000f468000 [REG:RW-] (sig_stack) measured
    000000000f448000-000000000f458000 [REG:RW-] (sig_stack) measured
    000000000ae2f000-000000000ae70000 [REG:R-X] (code) measured
    000000000b06f000-000000000f448000 [REG:RW-] (data) measured
    0000000000010000-000000000ae2f000 [REG:RWX] (free)
Measurement:
    5d44902f348a30f6ffed6ebd865e78451db3b4e1d418a5c89ef8315e9cb15546
graphene-sgx-get-token --output bash.token --sig bash.sig
Attributes:
    mr_enclave:  5d44902f348a30f6ffed6ebd865e78451db3b4e1d418a5c89ef8315e9cb15546
    mr_signer:   e354d37d6a9962aea4e2b3d4f45c398b21d1c0fb89f1ac4e3ace4f209cba5461
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0600000000000000
    attr.xfrm:   e702000000000000
    misc_select: 00000000
    misc_mask:   00000000
    modulus:     59f2be8eaea21a8226183f0323845af3...
    exponent:    3
    signature:   6a91086e128d26e4a38984920cc30624...
    date:        2021-08-05
```

## Steps to reproduce

`cd Examples/bash`
`ARCH_LIBDIR=/lib64 make SGX=1`
## Expected results
Manifest file generation, sgx-sign and token should pass.

## Actual results
graphene-sgx-sign fails with permission denied error

**Comment by dimakuv** [comment]
Thanks for the bug report.

This is because we have this: https://github.com/oscarlab/graphene/blob/80e36a6a1e91a43f8c33b64efacb61b697fdccff/Examples/bash/manifest.template#L33

This implies that `graphene-sgx-sign` utility will "unfold" the directory where `bash` is located (on CentOS, this is `/usr/bin`) and add **all its files and sub-directories** as Graphene trusted files.

Surprisingly, CentOS puts some random files like `/usr/bin/etc/gshadow` under this path. Such files have very restrictive permissions (probably only read permission for the root user), and so `graphene-sgx-sign` fails to open this file for read (for hashing purposes).

The correct solution to this problem would be to replace `sgx.trusted_files.execs = "file:{{ execdir }}/"` with a specific list of files needed to run Bash workloads, like this:
```
sgx.trusted_files.execs_bash = "file:{{ execdir }}/bash"
sgx.trusted_files.execs_bash = "file:{{ execdir }}/ls"
sgx.trusted_files.execs_bash = "file:{{ execdir }}/date"
... etc ...
```

Anyone willing to take this task?

**Comment by dimakuv** [comment]
Thanks for the bug report.

This is because we have this: https://github.com/oscarlab/graphene/blob/80e36a6a1e91a43f8c33b64efacb61b697fdccff/Examples/bash/manifest.template#L33

This implies that `graphene-sgx-sign` utility will "unfold" the directory where `bash` is located (on CentOS, this is `/usr/bin`) and add **all its files and sub-directories** as Graphene trusted files.

Surprisingly, CentOS puts some random files like `/usr/bin/etc/gshadow` under this path. Such files have very restrictive permissions (probably only read permission for the root user), and so `graphene-sgx-sign` fails to open this file for read (for hashing purposes).

The correct solution to this problem would be to replace `sgx.trusted_files.execs = "file:{{ execdir }}/"` with a specific list of files needed to run Bash workloads, like this:
```
sgx.trusted_files.execs_bash = "file:{{ execdir }}/bash"
sgx.trusted_files.execs_bash = "file:{{ execdir }}/ls"
sgx.trusted_files.execs_bash = "file:{{ execdir }}/date"
... etc ...
```

Anyone willing to take this task?

**Comment by dimakuv** [comment]
Thanks for the bug report.

This is because we have this: https://github.com/oscarlab/graphene/blob/80e36a6a1e91a43f8c33b64efacb61b697fdccff/Examples/bash/manifest.template#L33

This implies that `graphene-sgx-sign` utility will "unfold" the directory where `bash` is located (on CentOS, this is `/usr/bin`) and add **all its files and sub-directories** as Graphene trusted files.

Surprisingly, CentOS puts some random files like `/usr/bin/etc/gshadow` under this path. Such files have very restrictive permissions (probably only read permission for the root user), and so `graphene-sgx-sign` fails to open this file for read (for hashing purposes).

The correct solution to this problem would be to replace `sgx.trusted_files.execs = "file:{{ execdir }}/"` with a specific list of files needed to run Bash workloads, like this:
```
sgx.trusted_files.execs_bash = "file:{{ execdir }}/bash"
sgx.trusted_files.execs_bash = "file:{{ execdir }}/ls"
sgx.trusted_files.execs_bash = "file:{{ execdir }}/date"
... etc ...
```

Anyone willing to take this task?

**Comment by mkow** [comment]
Hmm, I got a new idea: What if we just skipped inaccessible files in trusted files recursive scan? We can emit a warning that something is being skipped, but let the generation finish.

**Comment by aniket-intelx** [comment]
In the recent nightly runs, we are seeing the permission denied for `'/usr/bin/chfn'`

**Comment by dimakuv** [comment]
@aniket-intelx What is this file?

**Comment by aniket-intelx** [comment]
Please find the attached file for error message. Also, let me know if you need the manifest file.
[Bash.txt](https://github.com/gramineproject/graphene/files/7370100/Bash.txt)

**Comment by dimakuv** [comment]
@aniket-intelx I meant: what is the purpose of this file, what data it contains, what permissions it has, etc. Looks like it requires root to access it https://www.ibm.com/docs/fr/aix/7.1?topic=c-chfn-command.

Can you skip this file? Like, did you do any trick to skip `/usr/bin/etc/gshadow`?

Otherwise the only way would be to run Bash as root for now, and wait for the enhancement in Gramine suggest by @mkow above ("skip inaccessible files").

**Comment by dimakuv** [comment]
Actually, @boryspoplawski @mkow @woju This "skip inaccessible files" shouldn't be too hard to implement, right? We just need to tweak our Python gramine-manifest file. Could anyone do this fix?

**Comment by boryspoplawski** [comment]
I'll do it
