### ISSUE TITLE
GSC fails to sign container image

### ISSUE THREAD

**Issue by ratnadeepb** [oscarlab/graphene#2636]
## Description of the problem
```
Exception: Cannot resolve "file:/usr/local/lib/python3.8/dist-packages/pandas/tests/io/data/legacy_pickle/1.2.4/empty_frame_v1_2_4-GH or the file does not exist.
```
when running 
```
sudo ./gsc sign-image <docker_name> enclave-key.pem
```

## Steps to reproduce

The issue won't reproduce on the current master branch. I am following up on [this](https://github.com/oscarlab/graphene/issues/2435) issue.
```
git clone http://github.com/oscarlab/graphene
cd graphene/Tools/gsc
cp config.yaml.template config.yaml
sed -i "s/2e737e69f076c60918f87d6829bb769925e75fec/a743b6a83b4f3587e1d72b53509239c21d3c1231/g" config.yaml
sudo apt install python3 python3-pip
sudo pip3 install docker jinja2 toml pyyaml

sudo ./gsc build --insecure-args <docker_name> ./test/ubuntu18.04-pytorch.manifest -nc --rm

openssl genrsa -3 -out enclave-key.pem 3072
sudo ./gsc sign-image <docker_name> enclave-key.pem
```

## Expected results
A signed copy of the container being created.

## Actual results
Fails with the following error:
```
Step 7/11 : RUN /graphene/python/graphene-sgx-sign         -libpal /graphene/Runtime/libpal-Linux-SGX.so         -key /gsc-signer-key.pem         -manifest /entrypoint.manifest         -output /entrypoint.manifest.sgx

 ---> Running in 3102aa0715d3
Attributes:
    size:        0x100000000
    thread_num:  32
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0600000000000000
    attr.xfrm:   0300000000000000
    misc_select: 00000000
    date:        2021-08-10
Trusted files:
Traceback (most recent call last):
  File "/graphene/python/graphene-sgx-sign", line 5, in <module>
    sys.exit(main())
  File "/graphene/python/graphenelibos/sgx_sign.py", line 851, in main
    return main_sign(args)
  File "/graphene/python/graphenelibos/sgx_sign.py", line 774, in main_sign
    for key, val in get_trusted_files(manifest).items():
  File "/graphene/python/graphenelibos/sgx_sign.py", line 242, in get_trusted_files
    targets[key] = (val, resolve_uri(val, check_exist))
  File "/graphene/python/graphenelibos/sgx_sign.py", line 211, in resolve_uri
    raise Exception(
Exception: Cannot resolve "file:/usr/local/lib/python3.8/dist-packages/pandas/tests/io/data/legacy_pickle/1.2.4/empty_frame_v1_2_4-GH or the file does not exist.

Removing intermediate container 3102aa0715d3
Failed to build a signed graphenized Docker image `<docker_name>`.
```

**Comment by mkow** [comment]
Hehe, I think I know what's the problem :) This missing file name (`empty_frame_v1_2_4-GH`) looked suspicious to me, so I googled it, and it turns out that it's actually named `empty_frame_v1_2_4-GH#42345.pkl`. The rest of the story should be obvious now :)

@ratnadeepb: Could you check `/entrypoint.manifest` for this specific entry? The question is on which layer the hash is not properly escaped. I guess it's on the TOML layer, but that's something to verify.

**Comment by mkow** [comment]
Ok, I found the bug, it's actually in GSC, not Graphene's TOML handling. Can you add missing doublequotes around the file path in https://github.com/oscarlab/graphene/blob/b9e151748d66be80d1e20cfa0513fc44f1cbe85b/Tools/gsc/finalize_manifest.py#L81 and check again?

**Comment by dimakuv** [comment]
@mkow I don't think this is a bug in GSC. The relevant code snippet is this: https://github.com/oscarlab/graphene/blob/b9e151748d66be80d1e20cfa0513fc44f1cbe85b/Tools/gsc/finalize_manifest.py#L75-L81

So you can see that we add some escaping and we put contents of the `trusted_file_entry` in doublequotes. Otherwise TOML parsing wouldn't work at all.

But I agree that the bug is somewhere inside GSC (just not in this particular place). Looking at `/entrypoint.manifest` should give us a hint.

**Comment by mkow** [comment]
Ah, that's a bit confusing that the quotes are added there instead of on that line I quoted :)

Btw. I just found a bug related to these doublequotes, but probably unrelated: there's that `if trusted_file_entry in already_added_files:`, but if I see correctly, `already_added_files` contains just file URIs, without escaping?

**Comment by dimakuv** [comment]
> Btw. I just found a bug related to these doublequotes, but probably unrelated: there's that if trusted_file_entry in already_added_files:, but if I see correctly, already_added_files contains just file URIs, without escaping?

I don't think it's true because the input TOML manifest (created by the user) must contain *already escaped* file URIs. Otherwise it is not a proper TOML file. In other words, the writer of the input manifest is to blame :)

We even have the comment about this:
https://github.com/oscarlab/graphene/blob/b9e151748d66be80d1e20cfa0513fc44f1cbe85b/Tools/gsc/finalize_manifest.py#L24

**Comment by dimakuv** [comment]
Yes, we should move GSC to use a proper TOML parser (`import toml`) instead of this hand-crafted parsing. Basically, that's what the TODO comment says. The bug is probably because of this hand-crafted parsing, yes.

**Comment by ratnadeepb** [comment]
I got slightly lost here. Is the signing issue being caused by incorrect toml handling?

**Comment by mkow** [comment]
Yes, most likely.
