### ISSUE TITLE
/graphene/Examples/pytorch/  Error

### ISSUE THREAD

**Issue by Jacinda-Guo** [oscarlab/graphene#2643]
# Description of the problem
graphene: v1.2-rc1
Ubuntu 18.04
Linux 4.15.0
Graphene has been compiled and installed successfully. The `graphene-sgx helloworld` command is run successfully. 
The dependency was installed in the /Examples/ pytorch/ directory as described in the document and compiled successfully.

# Steps to reproduce
Refer to the link: [https://github.com/oscarlab/graphene/tree/v1.2-rc1/Examples/pytorch](https://github.com/oscarlab/graphene/tree/v1.2-rc1/Examples/pytorch)
```
sudo apt install libnss-mdns libnss-myhostname
sudo apt install python3-pip lsb-release
pip3 install --user torchvision pillow
make download_model
make PYTHONPATH=<python install path> PYTHONVERSION=python3.6 SGX=1
```

# Results
Then `sudo python3 pytorchexample.py` and `sudo graphene-direct ./pytorch ./pytorchexample.py` commands are run successfully and the result.txt file is generated.’
```
sdp@sgx:/opt/graphene/Examples/pytorch$ rm result.txt 
sdp@sgx:/opt/graphene/Examples/pytorch$ python3 pytorchexample.py 
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
sdp@sgx:/opt/graphene/Examples/pytorch$ echo $?
0
sdp@sgx:/opt/graphene/Examples/pytorch$ ll result.txt 
-rw-rw-r-- 1 sdp sdp 218 Aug 12 02:12 result.txt
sdp@sgx:/opt/graphene/Examples/pytorch$ 
```
```
sdp@sgx:/opt/graphene/Examples/pytorch$ rm result.txt  
sdp@sgx:/opt/graphene/Examples/pytorch$ graphene-direct ./pytorch ./pytorchexample.py 
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
error: Forwarding host environment variables to the app is enabled. Graphene will continue application execution, but this configuration must not be used in production!
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
sdp@sgx:/opt/graphene/Examples/pytorch$ echo $?
0
sdp@sgx:/opt/graphene/Examples/pytorch$ ll result.txt 
-rw-rw-r-- 1 sdp sdp 218 Aug 12 02:15 result.txt
```

However, the following error occurs when executing command: `graphene-sgx ./pytorch ./pytorchexample.py` 
```
sdp@sgx:/opt/graphene/Examples/pytorch$ rm result.txt 
sdp@sgx:/opt/graphene/Examples/pytorch$ graphene-sgx ./pytorch ./pytorchexample.py 
error: Could not find size of file: file:/usr/lib/python3.6/__pycache__/__future__.cpython-36.pyc.1792161696
error: Failed to load the checksums of trusted files: -6
sdp@sgx:/opt/graphene/Examples/pytorch$ sudo graphene-sgx ./pytorch ./pytorchexample.py 
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
error: Forwarding host environment variables to the app is enabled. Graphene will continue application execution, but this configuration must not be used in production!
Traceback (most recent call last):
  File "./pytorchexample.py", line 4, in <module>
    from torchvision import models
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/torchvision/__init__.py'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 25, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 35, in <module>
    apt_pkg.init_system()
apt_pkg.Error: E:Error reading the CPU table

Original exception was:
Traceback (most recent call last):
  File "./pytorchexample.py", line 4, in <module>
    from torchvision import models
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/torchvision/__init__.py'
sdp@sgx:/opt/graphene/Examples/pytorch$ echo $?
1
sdp@sgx:/opt/graphene/Examples/pytorch$ 
```

**Comment by sahason** [comment]
@mkow Please assign this to me.
