### ISSUE TITLE
File Listener Based on INOTIFY Throws Error

### ISSUE THREAD

**Issue by Cosmin2106** [oscarlab/graphene#2696]
## Problem description
Hi! I am trying to run a Java application compiled with GraalVM inside Graphene SGX. The scope of my prototype is to continuously watch an unprotected folder (added to the manifest via *sgx.allowed_files = ["file:<folder>"]*) for modifications. For that, I use the command **FileSystems.getDefault().newWatchService();**, which, in turn, uses **inotify** at system level.

Even though such an application can open and read unprotected folders and files, listening for file changes inside a folder breaks the application. Below, I attached a snippet of the code that breaks the application, together with the console output.

```
if (target.exists()) {
 System.out.println(">>>> Folder exists!");
  WatchService watcher = null;
  try {
     watcher = FileSystems.getDefault().newWatchService();   # here it breaks, inotify implementation
  } catch (IOException e) {
      e.printStackTrace();
  }
...
}
```
Console output:
```
2021-11-04 13:51:58,077 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2021-11-04 13:51:58,146 INFO  [org.apa.cam.mai.BaseMainSupport] (main) Auto-configuration summary
2021-11-04 13:51:58,147 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     camel.context.name=quarkus-camel-example-timer-log-xml
>>>> Folder exists!
java.io.IOException: Function not implemented
	at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
	at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
	at org.acme.xml.RouteScanner.configure(RouteScanner.java:31)
	at org.apache.camel.builder.RouteBuilder.checkInitialized(RouteBuilder.java:541)
	at org.apache.camel.builder.RouteBuilder.configureRoutes(RouteBuilder.java:487)
	at org.apache.camel.builder.RouteBuilder.addRoutesToCamelContext(RouteBuilder.java:462)
	at org.acme.xml.RouteScanner_ClientProxy.addRoutesToCamelContext(RouteScanner_ClientProxy.zig:2909)
	at org.apache.camel.impl.engine.AbstractCamelContext.addRoutes(AbstractCamelContext.java:1150)
	at org.apache.camel.main.RoutesConfigurer.configureRoutes(RoutesConfigurer.java:211)
	at org.apache.camel.quarkus.main.CamelMain.configureRoutes(CamelMain.java:70)
	at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:555)
	at org.apache.camel.quarkus.main.CamelMain.initCamelContext(CamelMain.java:116)
	at org.apache.camel.quarkus.main.CamelMain.doInit(CamelMain.java:86)
	at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
	at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:137)
	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy_0(CamelBootstrapProcessor$boot-173480958.zig:101)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy(CamelBootstrapProcessor$boot-173480958.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:515)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
2021-11-04 13:51:58,156 ERROR [org.apa.cam.qua.mai.CamelMainRuntime] (main) Failed to start application: java.lang.NullPointerException
	at sun.nio.fs.UnixPath.register(UnixPath.java:916)
	at java.nio.file.Path.register(Path.java:894)
	at org.acme.xml.RouteScanner.configure(RouteScanner.java:38)
	at org.apache.camel.builder.RouteBuilder.checkInitialized(RouteBuilder.java:541)
	at org.apache.camel.builder.RouteBuilder.configureRoutes(RouteBuilder.java:487)
	at org.apache.camel.builder.RouteBuilder.addRoutesToCamelContext(RouteBuilder.java:462)
	at org.acme.xml.RouteScanner_ClientProxy.addRoutesToCamelContext(RouteScanner_ClientProxy.zig:2909)
	at org.apache.camel.impl.engine.AbstractCamelContext.addRoutes(AbstractCamelContext.java:1150)
	at org.apache.camel.main.RoutesConfigurer.configureRoutes(RoutesConfigurer.java:211)
	at org.apache.camel.quarkus.main.CamelMain.configureRoutes(CamelMain.java:70)
	at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:555)
	at org.apache.camel.quarkus.main.CamelMain.initCamelContext(CamelMain.java:116)
	at org.apache.camel.quarkus.main.CamelMain.doInit(CamelMain.java:86)
	at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
	at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:137)
	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy_0(CamelBootstrapProcessor$boot-173480958.zig:101)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy(CamelBootstrapProcessor$boot-173480958.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:515)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)

2021-11-04 13:52:00,328 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.NullPointerException
	at sun.nio.fs.UnixPath.register(UnixPath.java:916)
	at java.nio.file.Path.register(Path.java:894)
	at org.acme.xml.RouteScanner.configure(RouteScanner.java:38)
	at org.apache.camel.builder.RouteBuilder.checkInitialized(RouteBuilder.java:541)
	at org.apache.camel.builder.RouteBuilder.configureRoutes(RouteBuilder.java:487)
	at org.apache.camel.builder.RouteBuilder.addRoutesToCamelContext(RouteBuilder.java:462)
	at org.acme.xml.RouteScanner_ClientProxy.addRoutesToCamelContext(RouteScanner_ClientProxy.zig:2909)
	at org.apache.camel.impl.engine.AbstractCamelContext.addRoutes(AbstractCamelContext.java:1150)
	at org.apache.camel.main.RoutesConfigurer.configureRoutes(RoutesConfigurer.java:211)
	at org.apache.camel.quarkus.main.CamelMain.configureRoutes(CamelMain.java:70)
	at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:555)
	at org.apache.camel.quarkus.main.CamelMain.initCamelContext(CamelMain.java:116)
	at org.apache.camel.quarkus.main.CamelMain.doInit(CamelMain.java:86)
	at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
	at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:137)
	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy_0(CamelBootstrapProcessor$boot-173480958.zig:101)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy(CamelBootstrapProcessor$boot-173480958.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:515)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
```
Note that `java.io.IOException: Function not implemented` refers to the line highlighted in the code snippet above. I know that the approach I took is a bit unconventional, but I would be grateful to know how to get past the **inotify** problem, or which other alternatives there are in order to listen for file changes. Thank you!

**Comment by mkow** [comment]
Hi,

This repo is not used anymore (please see the readme). The project was migrated to https://github.com/gramineproject/gramine/. Please also ensure that you tested the most recent master and the bug still reproduces, we might have fixed the problem in the meantime.
