### ISSUE TITLE
the native example 'exec_fork' doesn't work

### ISSUE THREAD

**Issue by cryptograph** [oscarlab/graphene#62]
Hi there,

The program 'exec_fork' from the native folder hangs during execution in both SGX and noSGX modes. I followed the manual and all other native programs worked fine for me.

It would be great if you guys can take a look at it!

You can find my log file in an attach. 
Thank you!

[out_nosgx.txt](https://github.com/oscarlab/graphene/files/1038469/out_nosgx.txt)
[out_sgx.txt](https://github.com/oscarlab/graphene/files/1038471/out_sgx.txt)

**Comment by cryptograph** [comment]
Just want to update some info: the version of SGX-driver is 'cec111a' from March 23rd.

**Comment by mkow** [comment]
FYI: Unfortunately still reproducible on the current master (https://github.com/oscarlab/graphene/tree/34b8eb1ec2b23d5538d8ede385eb1be50e29354d)

**Comment by boryspoplawski** [comment]
There's some issue in relocation code (last child segfaults), didn't debug further:
```
Thread 3.1 "libpal.so" received signal SIGSEGV, Segmentation fault.
0x00007f7b0c172274 in resolve_map (strtab=0x7fffcd701670, ref=0x7fffcd701658) at elf/shim_rtld.c:142
142         if (ELFW(ST_BIND)((*ref)->st_info) != STB_LOCAL) {
(gdb) info threads 
  Id   Target Id         Frame 
  1.1  LWP 19637 "pal-Linux" 0x00007f327e9838ce in _DkEventWait (event=0x7f3282b90c50 <g_mem_pool+67038992>) at db_events.c:105
  1.2  LWP 19641 "pal-Linux" 0x00007f327e988aa9 in _DkStreamsWaitEvents (count=6, handle_array=0x7f327e6b4350, events=0x7f327e6b4550, ret_events=0x7f327e6b45d4, timeout_us=-1) at db_object.c:115
  2.1  LWP 19642 "libpal.so" 0x00007f3351a2307a in proc_read (handle=0x7f3355c27350 <g_mem_pool+67032592>, offset=0, count=4, buffer=0x6757e17867c4) at db_process.c:398
  2.2  LWP 19644 "libpal.so" 0x00007f3351a20aa9 in _DkStreamsWaitEvents (count=4, handle_array=0x7f335174c150, events=0x7f335174c350, ret_events=0x7f335174c3d4, timeout_us=-1) at db_object.c:115
* 3.1  process 19645 "libpal.so" 0x00007f7b0c172274 in resolve_map (strtab=0x7fffcd701670, ref=0x7fffcd701658) at elf/shim_rtld.c:142
(gdb) x/i $pc
=> 0x7f7b0c172274 <resolve_map+23>:     movzx  eax,BYTE PTR [rax+0x4]
(gdb) p/x $rax
$1 = 0xa0005b8
(gdb) bt
#0  0x00007f7b0c172274 in resolve_map (strtab=0x7fffcd701670, ref=0x7fffcd701658) at elf/shim_rtld.c:142
#1  0x00007f7b0c1727b8 in elf_machine_rela (l=0x7f7b0c132f90, reloc=0x400458, sym=0xa0005b8, reloc_addr_arg=0x401f0f00200bb4) at ../include/arch/x86_64/shim_dl-machine.h:69
#2  0x00007f7b0c172bb8 in elf_dynamic_do_rela (l=0x7f7b0c132f90, reladdr=4195416, relsize=216) at elf/do-rel.h:55
#3  0x00007f7b0c172a9f in _elf_dynamic_do_reloc (l=0x7f7b0c132f90, dt_reloc=7, dt_reloc_sz=8, do_reloc=0x7f7b0c172aac <elf_dynamic_do_rela>) at elf/rel.h:181
#4  0x00007f7b0c1759bf in do_relocate_object (l=0x7f7b0c132f90) at elf/shim_rtld.c:1195
#5  0x00007f7b0c1751ea in __load_elf_object (file=0x7f7b0c0fc048, addr=0x400000, type=2, remap=0x0) at elf/shim_rtld.c:953
#6  0x00007f7b0c175001 in load_elf_object (file=0x7f7b0c0fc048, addr=0x400000, mapped=2105344) at elf/shim_rtld.c:900
#7  0x00007f7b0c1764d1 in init_loader () at elf/shim_rtld.c:1454
#8  0x00007f7b0c14bda1 in shim_init (argc=0, args=0x7fffcd701ad8) at shim_init.c:509
#9  0x00007f7b0c161a2d in shim_start () at start-x86_64.S:37
#10 0x0000000000000000 in ?? ()
```

**Comment by dimakuv** [comment]
I just tested it, and it works.

**Comment by dimakuv** [comment]
Let me close this issue.
