### ISSUE TITLE
Change the get token socket addr

### ISSUE THREAD

**Issue by HuaiYuSched** [oscarlab/graphene#67]
Since the Intel SGX has change there local socket address[1] from sgx_aesm_socket_base to /var/run/aesmd/aesm.socket, the file Pal/src/host/Linux-SGX/signer/pal-sgx-get-token should change the socket addr too.    
Otherwise when you run ```make SGX_RUN=1``` in application ,this error will show
```
Traceback (most recent call last):
  File "/home/shenyouren/workspace/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token", line 168, in <module>
    token = connect_aesmd(attr)
  File "/home/shenyouren/workspace/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token", line 70, in connect_aesmd
    aesm_service.connect("\0sgx_aesm_socket_base" + "\0" * 87)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
../../../../../Pal/src///host/Linux-SGX/Makefile.Test:14: recipe for target 'python.token' failed
make: *** [python.token] Error 1 
```

here is the change:
```
 diff --git a/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token b/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token
index e72b86e..796667a 100755
--- a/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token
+++ b/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token
@@ -67,7 +67,7 @@ def connect_aesmd(attr):
     req_msg_raw = req_msg.SerializeToString()

     aesm_service = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
-    aesm_service.connect("\0sgx_aesm_socket_base" + "\0" * 87)
+    aesm_service.connect("/var/run/aesmd/aesm.socket" + "\0" * 81)

     aesm_service.send(struct.pack("<I", len(req_msg_raw)))
     aesm_service.send(req_msg_raw)
```
Ref
[1]. https://github.com/01org/linux-sgx/commit/65965c6ab61d103028b8b6a886b57e98ccf7ea9d

**Comment by chiache** [comment]
Submitted pull request #73. Thanks for reporting.
