### ISSUE TITLE
[LibOS] Emulate mlock/mlock2/munlock/etc family of syscalls

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#689]
Implement mlock, mlock2, munlock, mlockall, munlockall (lock and unlock memory). These can be stubbed easily by always returning success (Graphene cannot guarantee that the host OS will perform lock/unlock anyway, and a malicious OS will swap pages anyway).

This will allow to re-enable more LTP tests such as mincore02.

**Comment by dimakuv** [comment]
I don't know why this issue is marked as FS-related. @mkow ?

Anyway, this is very low priority. We haven't yet encountered any real-world applications that depend on these syscalls.

**Comment by mkow** [comment]
Oops, this was incorrectly linked. Fixed.

**Comment by mkow** [comment]
That's pretty bad. `mlock` would be easy to fake (because it's not semantically visible, it's only for performance). `membarrier` should be possible to implement, but quite hard in SGX model - we'd need to send signals to all threads and wait for their confirmations that they actually issued a barrier. No idea if there's any easier way...

**Comment by dimakuv** [comment]
From what I understood from the `dotnet/` GitHub comments (linked in Nils's reply above), .NET needs `mlock` but can live without `membarrier` (but with sub-par performance).

It could be a trivial exercise to add dummy `mlock/munlock` and check if .NET workloads still work... @Nirusu Do you care about performance of whatever .NET workload you're trying to enable? Will stub/dummy implementations of `mlock/munlock` be enough for your purposes? We can create a quick PR with these dummy implementations, and you could test your workload and report back.

**Comment by Nirusu** [comment]
Okay, so I experimented a bit with getting the CoreCLR (the .NET runtime) running. Here's what I found out:

- Faking `mlock` (& `munlock`?) to just return 0 is enough to pass.
- Running .NET 5.0 with the default GC configuration ("Workstation Garbage Collection") works pretty terrible, always running OOM during launch and crashing. Switching to the so-called ["Server Garbage Collection"](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/workstation-server-gc) helped. I applied it as a build flag for the application [like this](https://stackoverflow.com/questions/44134508/what-is-server-garbage-collection-in-asp-net-core) in the .csproj.
- This gets me running into user code, where my application dies due to not being able to run a FileSystemWatcher:
```bash
[P1:T1:cartservice] warning: Unsupported system call inotify_init
Unhandled exception. 
[P1:T6:cartservice] warning: Ignoring FUTEX_CLOCK_REALTIME flag
[P1:T6:cartservice] warning: Ignoring FUTEX_CLOCK_REALTIME flag
[P1:T1:cartservice] warning: Unsupported system call flock
[P1:T6:cartservice] warning: Ignoring FUTEX_CLOCK_REALTIME flag
[P1:T1:cartservice] warning: Unsupported system call flock
[... many more messages about missing flock and CLOCK_REALTIME ...]
System.IO.IOException: Function not implemented
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at <Program>$.<Main>$(String[] args) in /home/nils/microservices-demo/src/cartservice/src/Program.cs:line 19
```

But hey, at least it's running user code! So yeah, the last one is out-of-scope for this ticket I guess, but getting .NET runtime to run user code requires at least shimmed `mlock`/`munlock` + a bunch of tweaks to the GC settings.

**Comment by dimakuv** [comment]
...And .NET runtime seems adamant on requiring `flock` if an application uses the FileSystemWatcher class. Which we didn't implement in Graphene (to date) because "haven't yet encountered any real-world applications" :)

**Comment by dimakuv** [comment]
@Nirusu Out of curiousity: do you really want to run a .NET runtime inside the SGX enclave? :)

**Comment by Nirusu** [comment]
Haha, well the idea was to evaluate if it's possible to get this ["Microservice Demo"](https://github.com/GoogleCloudPlatform/microservices-demo) running in SGX with Graphene with little effort. There is just this one service running in .NET making trouble :)

Otherwise, I do not think .NET applications are really a high priority... maybe for some enterprise stuff, but yeah I rarely encounter .NET applications under Linux.
